import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Public_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

import ThemeProvider from "@/components/shared/ThemeProvider";




const publicSansHeading = Public_Sans({subsets:['latin'],variable:'--font-heading'});

const roboto = Roboto({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }: LayoutProps<"/">) {

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", roboto.variable, publicSansHeading.variable)}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
       
          <main className="min-h-full  flex flex-col">
              {children}
          </main>
          <Toaster position="top-center" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
